title: "Amber Ramsey" # your name (or website title) here
logo: "/images/CSUheadshot144.jpg" # your photo (or logo) here
description: | # your text below (remove <br> elements if you don't need line breaks)
  Soft Skills:
  Communication ~ Problem Solving ~ Organized
  Teamwork ~ Dependable ~ Creativity ~ Focused
  <br> <br>
  Technology Skills:
  Microsoft Office Suite ~ Google Services ~ Git
  Github ~ Command Line ~ Sublime ~ Visual Studio Code
  HTML ~ CSS ~ C++ ~ Java ~ Javascript ~ Perl ~ Shell ~ Visual Basic
  Hash Tables ~ Loops ~ Linked List ~ Arrays ~ etc.
  <br> <br>
  <a href="https://docs.google.com/document/d/1GE2j0K7DwDy1dIGv0gDwV8i0oFqSbrTz9cIEXFgoLJI/edit?usp=sharing">View My Resume</a> 
  <br> <br>
  <a href="https://www.linkedin.com/in/amber-ramsey-438368171">View My LinkedIn Profile</a> 
  
theme: "jekyll-theme-minimal"
google_analytics: "UA-000000-0" # your Google Analytics tracking ID here
